-- Let COPY carry explicit ids.
--
-- GENERATED ALWAYS rejects an explicit value unless the statement says
-- OVERRIDING SYSTEM VALUE, and COPY has no such clause. Backfilling a corpus
-- therefore could not preserve companies.id -- which boards.company_id
-- references, so remapping would mean rewriting every board on import.
--
-- BY DEFAULT keeps the sequence for normal inserts and simply allows an
-- explicit id when one is supplied. That is the behaviour any restore needs,
-- not just this one, so it belongs in the schema rather than in a script.

ALTER TABLE companies ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE events    ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE poll_runs ALTER COLUMN id SET GENERATED BY DEFAULT;
